version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    image: null-jobs-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  bootstrap:
    build:
        context: .
        dockerfile: Dockerfile
    image: null-jobs-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/workspace
    command: bash -c "python manage.py loaddata utils/seed/accounts/userauth.json && python manage.py loaddata utils/seed/jobs/company.json && python manage.py loaddata utils/seed/jobs/userprofile.json && python manage.py loaddata utils/seed/jobs/job.json"
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: null_jobs_backend_db
      MYSQL_USER: null_jobs_backend_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  caddy_data:
